services:
  - type: web
    name: newtest-line-bot
    env: python
    runtime: python-3.11
    plan: free   # หรือเปลี่ยนเป็น starter/standard ถ้าต้องการ
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FAQ_EXCEL_PATH
        value: "data/เทสบอท รอบท้าย.xlsx"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TZ
        value: "Asia/Bangkok"

# ออปชันเสริม: ถ้ามีงาน background task
# workers:
#   - type: worker
#     name: line-bot-worker
#     env: python
#     runtime: python-3.11
#     buildCommand: pip install --no-cache-dir -r requirements.txt
#     startCommand: python app/worker.py
